'use client'

import { useState } from 'react'
import { ArrowRight, Coffee, Heart, Instagram, Facebook, Twitter, MapPin, Phone, Mail, Search, ShoppingBag, Plus, Star, Menu as MenuIcon, X } from 'lucide-react'

const photo = (id: string, width = 900) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`
const categories = [
  { name: 'Coffee', desc: 'Your daily little ritual', image: 'photo-1442512595331-e89e73853f31' },
  { name: 'Pastries', desc: 'Baked fresh every morning', image: 'photo-1555507036-ab1f4038808a' },
  { name: 'Desserts', desc: 'A little something sweet', image: 'photo-1578985545062-69928b1d9587' },
  { name: 'Cold Drinks', desc: 'Cool sips, sunny days', image: 'photo-1461023058943-07fcbe16d735' },
]
const products = [
  { name: 'Caramel Latte', description: 'Espresso, steamed milk & house caramel', price: '5.50', rating: '4.9', label: 'Bestseller', image: 'photo-1461023058943-07fcbe16d735' },
  { name: 'Classic Cappuccino', description: 'Rich espresso with a cloud of silky foam', price: '4.80', rating: '4.8', label: 'House favorite', image: 'photo-1570968915860-54d5c301fa9f' },
  { name: 'Strawberry Cheesecake', description: 'Creamy vanilla, berries & buttery crumb', price: '6.20', rating: '5.0', label: 'Made in house', image: 'photo-1533134242443-d4fd215305ad' },
  { name: 'Iced Matcha', description: 'Ceremonial matcha, oat milk & a little honey', price: '5.00', rating: '4.9', label: 'Feel good sip', image: 'photo-1515823064-d6e0c04616a7' },
  { name: 'Chocolate Croissant', description: 'Flaky, golden layers with dark chocolate', price: '3.80', rating: '4.9', label: 'Baked today', image: 'photo-1555507036-ab1f4038808a' },
  { name: 'Mocha Frappe', description: 'Cold brew blended with cocoa & cream', price: '5.80', rating: '4.8', label: 'A cool classic', image: 'photo-1461023058943-07fcbe16d735' },
]
const gallery = [
  { label: 'Our sunlit corner', image: 'photo-1445116572660-236099ec97a0' },
  { label: 'Made with care', image: 'photo-1495474472287-4d71bcdd2085' },
  { label: 'A little latte love', image: 'photo-1534778101976-62847782c213' },
  { label: 'Fresh from the oven', image: 'photo-1509440159596-0249088772ff' },
  { label: 'Good days, together', image: 'photo-1521017432531-fbd92d768814' },
]
const reviews = [
  { name: 'Maya R.', role: 'Local regular', review: 'The kind of place that makes an ordinary Tuesday feel special. The oat latte is a little piece of heaven.', avatar: 'photo-1534528741775-53994a69daeb' },
  { name: 'James L.', role: 'Coffee enthusiast', review: 'Thoughtful coffee, the loveliest people, and the best croissant in the neighborhood. I could stay all day.', avatar: 'photo-1500648767791-00dcc994a43e' },
  { name: 'Sofia K.', role: 'Weekend visitor', review: 'A warm, beautiful space with treats that taste as good as they look. Already planning my next visit.', avatar: 'photo-1531123897727-8f129e1688ce' },
]

function Brand() { return <a className="brand" href="#home" aria-label="Brew and Bloom home"><span className="brand-mark"><Coffee /></span><span>Brew <span style={{ color: '#a87552' }}>&</span> Bloom</span></a> }
function Header({ cart }: { cart: number }) {
  const [searchOpen, setSearchOpen] = useState(false)
  const [mobileOpen, setMobileOpen] = useState(false)
  return <><header className="topbar"><div className="shell topbar-inner"><Brand /><div className="actions"><button className="icon-btn" aria-label="Search menu" onClick={() => setSearchOpen(!searchOpen)}>{searchOpen ? <X size={19} /> : <Search size={19} />}</button><a className="icon-btn" href="#favorites" aria-label={`Shopping bag, ${cart} items`}><ShoppingBag size={19} />{cart > 0 && <span className="cart-count">{cart}</span>}</a><a className="pill order-btn" href="#favorites">Order now <ArrowRight size={15} /></a><button className="icon-btn mobile-menu" aria-label="Toggle navigation" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <MenuIcon />}</button></div></div>{searchOpen && <form className="search-pop" onSubmit={e => { e.preventDefault(); document.querySelector('#favorites')?.scrollIntoView({ behavior: 'smooth' }); setSearchOpen(false) }}><Search size={16} /><input autoFocus placeholder="Search coffee, pastries..." aria-label="Search menu" /><button type="submit">Find it</button></form>}</header><nav className={`nav-wrap ${mobileOpen ? 'nav-open' : ''}`} aria-label="Main navigation"><div className="nav">{[['Home','#home'],['Menu','#favorites'],['About','#about'],['Specials','#specials'],['Gallery','#gallery'],['Contact','#contact']].map(([label,href],i)=><a className={i===0?'active':''} href={href} key={label} onClick={()=>setMobileOpen(false)}>{label}</a>)}</div></nav></>
}
function Hero() { return <section className="hero" id="home"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow">Your neighborhood happy place</span><h1>Good Coffee.<br/><span>Good Mood.</span></h1><p>Freshly brewed coffee, handcrafted treats, and cozy moments made for you.</p><div className="hero-buttons"><a className="pill" href="#favorites">Explore menu <ArrowRight size={16}/></a><a className="pill pill-light" href="#favorites">Order coffee</a></div><div className="hero-note"><div className="avatar-stack">{reviews.map(r=><img key={r.name} src={photo(r.avatar,100)} alt="" />)}</div><span><strong>4.9/5</strong> from our lovely locals</span></div></div><div className="hero-visual"><img className="hero-photo" src={photo('photo-1495474472287-4d71bcdd2085',1200)} alt="A warm cup of coffee on a cafe table"/><div className="float-card"><span className="float-icon"><Heart size={19}/></span><span><strong>Made with a little love</strong><small>And really good coffee</small></span></div></div></div></section> }
function Categories() { return <section className="section" id="menu"><div className="shell"><div className="center-heading"><span className="eyebrow">A little something for everyone</span><h2 className="section-title">What’s on your mind?</h2><p className="section-sub">Find your feel good favorite, made fresh and served with a smile.</p></div><div className="category-grid">{categories.map(c=><a href="#favorites" className="category-card" key={c.name}><div className="category-img-wrap"><img src={photo(c.image,500)} alt={c.name}/></div><h3>{c.name}</h3><p>{c.desc}</p></a>)}</div></div></section> }
function PopularMenu({ onAdd }: { onAdd: () => void }) { return <section className="section" id="favorites" style={{paddingTop: '45px'}}><div className="shell"><div className="center-heading"><span className="eyebrow">The good stuff</span><h2 className="section-title">Our Favorites</h2><p className="section-sub">The cups and bites our regulars come back for, time and time again.</p></div><div className="menu-grid">{products.map(item=><article className="menu-card" key={item.name}><div className="menu-image"><img src={photo(item.image,700)} alt={item.name}/><span className="tag">{item.label}</span></div><div className="menu-info"><div className="menu-meta"><h3>{item.name}</h3><span className="rating"><Star size={13}/>{item.rating}</span></div><p>{item.description}</p><div className="menu-bottom"><span className="price">${item.price}</span><button className="add-btn" onClick={onAdd} aria-label={`Add ${item.name} to cart`}><Plus size={14}/> Add to cart</button></div></div></article>)}</div></div></section> }
function SpecialOffer() { return <section className="shell section" id="specials" style={{paddingTop:35,paddingBottom:45}}><div className="offer"><div className="offer-copy"><span className="eyebrow">A little something extra</span><h2>Sweet treat,<br/>happy you!</h2><p>Get 20% off your favorite coffee and dessert combo. Because the best things are even better together.</p><a href="#favorites" className="pill">Grab the deal <ArrowRight size={15}/></a></div><div className="offer-image"><img src={photo('photo-1488477181946-6428a0291777',800)} alt="A freshly made cafe dessert" /></div></div></section> }
function About() { return <section className="section" id="about"><div className="shell about-grid"><div className="about-visual"><img className="about-main" src={photo('photo-1445116572660-236099ec97a0',900)} alt="The welcoming interior of Brew and Bloom cafe"/><img className="about-small" src={photo('photo-1511920170033-f8396924c348',500)} alt="A barista preparing a fresh cappuccino"/></div><div className="about-copy"><span className="eyebrow">A seat saved just for you</span><h2 className="section-title">More than<br/>just coffee</h2><p className="section-sub">At Brew & Bloom, we believe great coffee brings people together. From carefully selected beans to freshly baked treats, every detail is made to create a warm and memorable experience.</p><a className="pill" href="#gallery">Our little story <ArrowRight size={15}/></a><div className="stats"><div className="stat"><strong>10+</strong><span>Years of passion</span></div><div className="stat"><strong>25+</strong><span>Coffee blends</span></div><div className="stat"><strong>50K+</strong><span>Happy customers</span></div></div></div></div></section> }
function ExperienceGallery() { return <section className="section" id="gallery" style={{paddingTop:35}}><div className="shell"><div className="center-heading"><span className="eyebrow">Little moments, big feelings</span><h2 className="section-title">Come on in</h2><p className="section-sub">A peek at the cozy corners and everyday magic waiting for you.</p></div><div className="gallery-grid">{gallery.map((g,i)=><div className="gallery-item" key={g.label}><img src={photo(g.image,700)} alt={g.label}/><span className="gallery-label">{g.label}</span></div>)}</div></div></section> }
function Testimonials() { return <section className="section" style={{paddingTop:35}}><div className="shell"><div className="center-heading"><span className="eyebrow">Kind words from our corner</span><h2 className="section-title">People love Brew & Bloom</h2></div><div className="reviews">{reviews.map(r=><article className="review-card" key={r.name}><div className="stars" aria-label="5 out of 5 stars">{[1,2,3,4,5].map(n=><Star key={n} size={14} fill="currentColor"/>)}</div><blockquote>“{r.review}”</blockquote><div className="review-person"><img src={photo(r.avatar,120)} alt=""/><div><strong>{r.name}</strong><span>{r.role}</span></div></div></article>)}</div></div></section> }
function Newsletter() { const [sent,setSent]=useState(false); return <section className="section" style={{paddingTop:35}}><div className="shell"><div className="newsletter"><span className="eyebrow">A note from your favorite cafe</span><h2 className="section-title">Stay in the brew</h2><p>Get fresh offers, new menu updates and cafe stories directly in your inbox.</p><form className="email-form" onSubmit={e=>{e.preventDefault();setSent(true)}}><input type="email" required placeholder="Enter your email" aria-label="Email address"/><button className="pill" type="submit">Subscribe <ArrowRight size={15}/></button></form>{sent&&<p className="success-note" role="status">You’re on the list. Watch your inbox for a little sunshine!</p>}</div></div></section> }
function Footer() { return <footer className="footer" id="contact"><div className="shell"><div className="footer-grid"><div className="footer-about"><Brand/><p>Coffee, comfort and good vibes. Your neighborhood happy place, every day of the week.</p><div className="socials"><a href="https://instagram.com" aria-label="Instagram"><Instagram size={16}/></a><a href="https://facebook.com" aria-label="Facebook"><Facebook size={16}/></a><a href="https://x.com" aria-label="X"><Twitter size={16}/></a></div></div><div className="footer-col"><h4>Explore</h4><a href="#home">Home</a><a href="#favorites">Menu</a><a href="#about">About us</a><a href="#specials">Our specials</a></div><div className="footer-col"><h4>Say hello</h4><p><MapPin size={14} style={{display:'inline',marginRight:7}}/>18 Willow Lane, Portland</p><a href="tel:+15035550148"><Phone size={14} style={{display:'inline',marginRight:7}}/>+1 (503) 555-0148</a><a href="mailto:hello@brewandbloom.com"><Mail size={14} style={{display:'inline',marginRight:7}}/>hello@brewandbloom.com</a></div><div className="footer-col"><h4>Come by</h4><p>Mon–Fri · 7am–6pm</p><p>Weekends · 8am–5pm</p><a href="#contact">Privacy policy</a></div></div><div className="footer-bottom"><span>© 2025 Brew & Bloom. Made with care and good coffee.</span><span>Good things are brewing <Coffee size={13} style={{display:'inline',verticalAlign:'middle'}}/></span></div></div></footer> }
export default function Home() { const [cart,setCart]=useState(0); return <><Header cart={cart}/><main><Hero/><Categories/><PopularMenu onAdd={()=>setCart(v=>v+1)}/><SpecialOffer/><About/><ExperienceGallery/><Testimonials/><Newsletter/></main><Footer/></> }
